numbers = []
numbers.append(-1)
numbers.append(2)
numbers.append(5)
numbers.append(8)
numbers.append(10)
numbers.append(13)
names = ['Mateo', 'Danny']
names.append('James')
names.append('Thomas')
names.append('Luke')
print(numbers)
print(names)
print('numbers count = ', len(numbers))
print('names count = ', len(names))
